# Generated by Django 6.0.6 on 2026-06-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('createdatmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createdatmixin')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('game_class', models.CharField(choices=[('Warrior(Male)', 'Warrior(Male)'), ('Warrior(Female)', 'Warrior(Female)'), ('Mage', 'Mage'), ('Martial Artist(Female)', 'Martial Artist(Female)'), ('Martial Artist(Male)', 'Martial Artist(Male)'), ('Gunner(Male)', 'Gunner(Male)'), ('Gunner(Female)', 'Gunner(Female)'), ('Assassin', 'Assassin'), ('Specialist', 'Specialist'), ('Guardianknight', 'Guardianknight')], default='Warrior(Male)', max_length=25)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('can_be_saved', models.BooleanField(default=False)),
                ('requires_custom_file', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('common.createdatmixin',),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styles.style')),
            ],
        ),
        migrations.CreateModel(
            name='StyleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customizations/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='styles.style')),
            ],
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='styles/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='styles.style')),
            ],
        ),
    ]
