# Generated by Django 6.0.6 on 2026-06-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
